# Generated by Django 2.1.4 on 2018-12-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0003_bird'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
