# Generated by Django 2.1.4 on 2018-12-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0004_animal_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
