# Generated by Django 2.1.4 on 2018-12-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0005_bird_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='type',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bird',
            name='type',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
