# Generated by Django 2.1.4 on 2018-12-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0007_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('views', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('Animal', 'Animal'), ('Bird', 'Bird'), ('Insect', 'Insect')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.DeleteModel(
            name='Bird',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
