# Generated by Django 2.1.4 on 2018-12-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0008_auto_20181209_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='beast',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
